-- public 스키마에 todos 테이블을 생성합니다.
CREATE TABLE public.todos (
  -- id: 8바이트 정수, 자동 증가하는 기본 키로 설정
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- created_at: 타임존 포함 시간, 기본값은 현재 시간
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  -- title: 텍스트 타입, 빈 텍스트는 허용하지 않음
  title TEXT CHECK (char_length(title) > 0) NOT NULL,

  -- completed: 불리언 타입, 기본값은 false
  completed BOOLEAN DEFAULT false NOT NULL,

  -- user_id: Supabase 인증 사용자의 id를 참조하는 외래 키
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);

-- 테이블에 대한 설명 추가
COMMENT ON TABLE public.todos IS 'Todo list items';