POST https://n8n.elanvitaloffice.com/webhook-test/0a646f66-8799-485b-8f81-5d219316a729 HTTP/1.1
Content-Type: application/json

{
  "title": "오랜만에 만난 친구와의 저녁 식사 후기",
  "content": "퇴근 후 강남역에서 고등학교 동창들을 만났다. '테이스티 키친'의 파스타가 정말 맛있었고, 특히 명란 크림 파스타가 일품이었다. 최근 업무 때문에 쌓였던 스트레스가 대화하며 많이 풀렸다. 다음 모임은 한 달 뒤로 약속했는데, 그땐 여행 계획을 짜기로 했다. 내일 오전에는 9시 30분에 꼭 운동 가기!",
  "timestamp": "2025-12-08T10:51:19Z"
}